import AppHeader from "@/components/AppHeader"
import AppFooter from "@/components/AppFooter"
import '../styles/style.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function HomePageLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="main-layout">
                <AppHeader />
                {children}
                <AppFooter />
            </body>
        </html>
    )
}
